import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { AppQuery, AppTheme } from "@/contexts";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import "./globals.css";
import { Header } from "@/components/organisms/header";
import { ScrollToTop } from "@/components/organisms/scroll-to-top";
import { Footer } from "@/components/organisms/footer";

const font = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={`${font.className}`}>
        <AppQuery>
          <AppTheme>
            <NextIntlClientProvider>
              <Header />
              {children}
              <Footer />
              <ScrollToTop />
            </NextIntlClientProvider>
          </AppTheme>
        </AppQuery>
      </body>
    </html>
  );
}
